elasticsearch:
  port: ${ELASTIC_PORT:9200}
  host: ${ELASTIC_HOST:localhost}
  user: ${ELASTIC_USER:elastic}
  password: ${ELASTIC_PASSWORD:octo}
  ssl: ${ELASTIC_SSL:false}
  client:
    timeout: 2500
  socket:
    timeout: 2500


