elasticsearch:
  port: ${ELASTIC_PORT}
  host: ${ELASTIC_HOST}
  user: ${ELASTIC_USER:}
  password: ${ELASTIC_PASSWORD:}
  ssl: ${ELASTIC_SSL:false}
  client:
    timeout: 2500
  socket:
    timeout: 2500


